# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/base_rbt',
                'doc_host': 'https://hamish-haggerty.github.io',
                'git_url': 'https://github.com/hamish-haggerty/base_rbt',
                'lib_path': 'base_rbt'},
  'syms': {'base_rbt.model_base': {}}}