# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/dermnetufes_dataloading.ipynb.

# %% auto 0
__all__ = ['label_func', 'get_bt_dermnetufes_train_dls']

# %% ../nbs/dermnetufes_dataloading.ipynb 3
import torch
from fastai.vision.all import *
# from self_supervised.augmentations import *
# from self_supervised.layers import *
from .utils import *

# %% ../nbs/dermnetufes_dataloading.ipynb 4
def label_func(x):
    # Example label function, modify it according to your dataset's structure
    return ''

def get_bt_dermnetufes_train_dls(bs,size,device,pct_dataset=1.0,num_workers=12):

    fnames_ufes=[]
    for i in [1,2,3]:
        fnames_ufes+=get_image_files(f"/content/PAD_UFES_20_resized/imgs_part_{i}/imgs_part_{i}")

    base_train_dir = "/content/DermNetDataset/train"
    base_test_dir = "/content/DermNetDataset/test"
    fnames_train = get_image_files(base_train_dir)
    fnames_test = get_image_files(base_test_dir)
    fnames_derm = fnames_train + fnames_test #we are doing SSL so we can use all the data

    fnames = fnames_ufes*2 + fnames_derm
    n = int(len(fnames)*pct_dataset)
    
    dls = ImageDataLoaders.from_path_func(
        path=".",
        fnames=fnames[0:n],
        label_func=label_func,
        bs=bs,
        valid_pct=0,
        device=device,
        num_workers=num_workers*(device=='cuda')
                                          )
    
    return dls
 
