# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/hitheredeletelater.ipynb.

# %% auto 0
__all__ = ['x', 'foo']

# %% ../nbs/hitheredeletelater.ipynb 1
import math


# %% ../nbs/hitheredeletelater.ipynb 2
x=math.pi

# %% ../nbs/hitheredeletelater.ipynb 3
def foo():
    return math.pi

