# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/isicufes_dataloading.ipynb.

# %% auto 0
__all__ = ['get_bt_isicufes_train_dls']

# %% ../nbs/isicufes_dataloading.ipynb 2
#directory = "/content/drive/MyDrive/ISIC_2019_Training_Input/"

# %% ../nbs/isicufes_dataloading.ipynb 4
from fastai.vision.all import *
# from self_supervised.augmentations import *
# from self_supervised.layers import *
from .utils import *
import os


# %% ../nbs/isicufes_dataloading.ipynb 10
def get_bt_isicufes_train_dls(bs,
                          size, #not needed
                          device,
                          pct_dataset=1.0,
                          num_workers=12):

    dataset_dir = "/content/isic_dataset" #hardcoded for ssl.
    combined_resized_dir = os.path.join(dataset_dir, "ISIC_2019_TrainingValid_Resized")
    fnames_isic = get_image_files(combined_resized_dir)



    fnames_ufes=[]
    for i in [1,2,3]:
        fnames_ufes+=get_image_files(f"/content/PAD_UFES_20_resized/imgs_part_{i}/imgs_part_{i}")
    
    fnames = fnames_isic+fnames_ufes
    n = int(len(fnames)*pct_dataset)

    dls = ImageDataLoaders.from_path_func(
        path=".",
        fnames=fnames[0:n],
        label_func=lambda x: '',
        bs=bs,
        valid_pct=0,
        device=device,
        num_workers=num_workers*(device=='cuda')
                                          )
    return dls

