# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/model_base.ipynb.

# %% auto 0
__all__ = ['device']

# %% ../nbs/model_base.ipynb 4
import self_supervised
import torch
device='cuda' if torch.cuda.is_available() else 'cpu'
from fastai.vision.all import *
